version: '3.8'

services:
  splitflap:
    build: .
    container_name: splitflap-display
    ports:
      - "8001:8001"
    environment:
      - SPLITFLAP_API_KEY=${SPLITFLAP_API_KEY:-}
      - PORT=8001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8001/api/status')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      # Mount for development (optional)
      - ./:/app
    labels:
      - "com.splitflap.description=Split-Flap Display Server"
      - "com.splitflap.version=2.0.0"